input_ok = '''
            form-control 
            block w-full 
            px-3 
            py-3 
            text-base 
            font-normal 
            text-gray-700 
            bg-white 
            bg-clip-padding 
            border 
            border-solid 
            border-gray-300 
            transition 
            ease-in-out 
            m-0 
            focus:text-gray-700 
            focus:bg-white 
            focus:border-blue-600 
            focus:outline-none
            '''
input_error = '''
            form-control 
            block w-full 
            px-3 
            py-3 
            text-base 
            font-normal 
            text-red-700 
            bg-white 
            bg-clip-padding 
            border 
            border-solid 
            border-red-500 
            transition 
            ease-in-out 
            m-0 
            focus:text-red-700 
            focus:bg-white 
            focus:border-blue-600 
            focus:outline-none
            '''
submit = '''
        w-full 
        mt-5 
        px-6 
        py-3 
        bg-blue-600 
        text-white
        font-medium 
        text-medium 
        leading-tight 
        uppercase 
        shadow-md
        hover:bg-blue-700 
        hover:shadow-lg 
        focus:bg-blue-700 
        focus:shadow-lg 
        focus:outline-none 
        focus:ring-0 
        active:bg-blue-800 
        active:shadow-lg
        transition 
        duration-150 
        ease-in-out 
        cursor-pointer
        '''
input_main = '''
            form-control 
            block w-full 
            px-3 
            py-5 
            text-base 
            text-center
            text-5xl 
            text-gray-700 
            bg-white 
            bg-clip-padding 
            border 
            border-solid 
            border-gray-300 
            transition 
            ease-in-out 
            m-0 
            focus:text-gray-700 
            focus:bg-white 
            focus:border-blue-600 
            focus:outline-none
            '''

error_main = '''
            form-control 
            block w-full 
            px-3 
            py-5 
            text-base 
            text-center
            text-5xl 
            text-red-700 
            bg-white 
            bg-clip-padding 
            border 
            border-solid 
            border-red-500 
            transition 
            ease-in-out 
            m-0 
            focus:text-red-700 
            focus:bg-white 
            focus:border-blue-600 
            focus:outline-none
            '''